/**
 **************************
 * @file           : keypad_interface.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 **************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 **************************
 */

#include <stdint.h>

#if !defined(_SOFT_FP) && defined(_ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void delay(int T)
{
	int i;
	while(T--)
	{
	for(i=0;i<1000;i++);
	}
}


int main(void)
{
	//Peripheral register addresses

	uint32_t *portcMODER =(uint32_t *)0x40020800;
	uint32_t *portcAHB1ENR =(uint32_t *)0x40023830;
	uint32_t *portcIDR =(uint32_t *)0x40020810;
	uint32_t *portcODR =(uint32_t *)0x40020814;

	uint32_t *portcPUPDR =(uint32_t *)0x4002080c;



	//rows-pc0-pc3=output
	//columns-pc4-pc7=input

	*portcAHB1ENR |= 0x4;                    //Enable the Peripheral clock for GPIOC.
	*portcMODER |= 0x55;                     //output mode.(pc0-pc3)
	*portcPUPDR |= 0x5500;                   //Input mode.(pc4-pc7)


	while(1)
	{
		//Make all rows HIGH
		*portcODR |= 0x0f;

		 //Make R1 LOW
		*portcODR &= ~(1<<0);

		//scan the columns

		//check C1(PD4) low or high
		if(!(*portcIDR & (1<<4)))
		{
			//key is pressed
			delay(1000);
			printf("1 pressed\n");
		}

		//check C1(PD5) low or high
		if(!(*portcIDR & (1<<5)))
		{
			//key is pressed
			delay(1000);
			printf("2 pressed\n");
		}

		//check C1(PD6) low or high
		if(!(*portcIDR & (1<<6)))
		{
			//key is pressed
			delay(1000);
			printf("3 pressed\n");
		}

		//check C1(PD7) low or high
		if(!(*portcIDR & (1<<7)))
		{
			//key is pressed
			delay(1000);
			printf("A pressed\n");
		}

		//Make all rows HIGH
		*portcODR |= 0x0f;

		//Make R2 LOW
		*portcODR &= ~(1<<1);

		//check C1(PD4) low or high
		if(!(*portcIDR & (1<<4)))
		{
			//key is pressed
			delay(1000);
			printf("4 pressed\n");
		}

		//check C1(PD5) low or high
		if(!(*portcIDR & (1<<5)))
		{
			//key is pressed
			delay(1000);
			printf("5 pressed\n");
		}

		//check C1(PD6) low or high
		if(!(*portcIDR & (1<<6)))
		{
			//key is pressed
			delay(1000);
			printf("6 pressed\n");
		}

		//check C1(PD7) low or high
		if(!(*portcIDR & (1<<7)))
		{
			//key is pressed
			delay(1000);
			printf("B pressed\n");
		}

		//Make all rows HIGH
		*portcODR |= 0x0f;

		//Make R3 LOW
		*portcODR &= ~(1<<2);

		//check C1(PD4) low or high
		if(!(*portcIDR & (1<<4)))
		{
			//key is pressed
			delay(1000);
			printf("7 pressed\n");
		}

		//check C1(PD5) low or high
		if(!(*portcIDR & (1<<5)))
		{
			//key is pressed
			delay(1000);
			printf("8 pressed\n");
		}

		//check C1(PD6) low or high
		if(!(*portcIDR & (1<<6)))
		{
			//key is pressed
			delay(1000);
			printf("9 pressed\n");
		}

		//check C1(PD7) low or high
		if(!(*portcIDR & (1<<7)))
		{
			//key is pressed
			delay(1000);
			printf("C pressed\n");
		}

		//Make all rows HIGH
		*portcODR |= 0x0f;

		//Make R4 LOW
		*portcODR &= ~(1<<3);

		//check C1(PD5) low or high
		if(!(*portcIDR & (1<<4)))
		{
			//key is pressed
			delay(1000);
			printf("* pressed\n");
		}

		//check C1(PD5) low or high
		if(!(*portcIDR & (1<<5)))
		{
			//key is pressed
			delay(1000);
			printf("0 pressed\n");
		}

		//check C1(PD6) low or high
		if(!(*portcIDR & (1<<6)))
		{
			//key is pressed
			delay(1000);
			printf("# pressed\n");
		}

		//check C1(PD7) low or high
		if(!(*portcIDR & (1<<7)))
		{
			//key is pressed
			delay(1000);
			printf("D pressed\n");
		}


		//End Of While Loop
	}


    /* Loop forever */
	for(;;);
}
